name: Deploy Terraform

on: [push, workflow_dispatch]

jobs:
  build:
    name: "Init and Plan Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        working-directory: ./env
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        run: terraform init

  #   uses: delarooster/Dlr.Yaml.Templates/.github/workflows/build-tf.yaml@main
  #   with:
  #     workingDirectory: "env/"
  #     targetEnvironment: "dev"
  #     resourceGroup: "rg-atd-test"
  #   secrets: inherit

  # deploy:
  #   uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-tf.yaml@main
  #   needs: build
  #   with:
  #     workingDirectory: "env/"
  #     targetEnvironment: "dev"
  #     resourceGroup: "rg-atd-test"
  #   secrets: inherit
