name: Deploy Terraform

on: [push, workflow_dispatch]

jobs:
  build:
    uses: delarooster/Dlr.Yaml.Templates/.github/workflows/build-tf.yaml@main
    with:
      workingDirectory: ./env
      targetEnvironment: "dev"
      resourceGroup: "rg-mesh-dev"
    secrets: inherit

  # deploy:
  #   uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-tf.yaml@main
  #   needs: build
  #   with:
  #     workingDirectory: "env/"
  #     targetEnvironment: "dev"
  #     resourceGroup: "rg-atd-test"
  #   secrets: inherit
